@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix cco: <http://www.ontologyrepository.com/CommonCoreOntologies/> .
@prefix obo: <http://purl.obolibrary.org/obo/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

<https://www.example.com/2024-10-23/are-we-the-baddies/skulls> rdf:type owl:Ontology ;
                                               owl:imports <http://www.ontologyrepository.com/CommonCoreOntologies/Mid/2024-09-26/MergedAllCoreOntology> ;
                                               dc:contributor "Jonathan M. Vajda" ;
                                               dc:license <https://creativecommons.org/licenses/by/4.0/> ;
                                               dcterms:description "BFO-CCO Conformance Skulls Graph is an RDF graph of anti-model ontology elements, which are designed to violate BFO-CCO conformance standards for the purpose of verifying that the quality control checks enforce specifications."@en ;
                                               owl:versionIRI <https://github.com/jonathanvajda/2024-10-22/cco-d-acts> ;
                                               owl:versionInfo "2024-10-23"@en ;
                                               rdfs:label "BFO-CCO Conformance Skulls Graph" .

                                               